CREATE TABLE IF NOT EXISTS user (
    playerId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(36) UNIQUE,
    userClass INT NOT NULL,
    userLevel INT NOT NULL,
    
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TABLE IF NOT EXISTS user_inventory (
--     id VARCHAR(36) PRIMARY KEY,
--     playerId INT NOT NULL,
--     FOREIGN KEY (playerId) REFERENCES user (playerId)
-- );