export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  C_ENTER : 0,
  S_ENTER : 1,
  S_SPAWN : 2,

  S_DESPAWN : 5,
  C_MOVE : 6,
  S_MOVE : 7,
  C_ANIMATION : 8,
  S_ANIMATION : 9,
  C_CHANGE_COSTUME : 10,
  S_CHANGE_COSTUME : 11,
  C_CHAT : 12,
  S_CHAT : 13,
  C_ENTER_DUNGEON : 14,
  C_PLAYER_RESPONSE : 15,
  S_ENTER_DUNGEON : 16,
  S_LEAVE_DUNGEON : 17,
  S_SCREEN_TEXT : 18,
  S_SCREEN_DONE : 19,
  S_BATTLE_LOG : 20,
  S_SET_PLAYER_HP : 21,
  S_SET_PLAYER_MP : 22,
  S_SET_MONSTER_HP : 23,
  S_PLAYER_ACTION : 24,
  S_MONSTER_ACTION : 25
};
