export const RESPONSE_SUCCESS_CODE = 0;

export const HANDLER_IDS = {
  C_ENTER : 0,
  C_MOVE : 6,
  C_ANIMATION : 8,
  C_CHANGE_COSTUME : 10,
  C_CHAT : 12,
  C_ENTER_DUNGEON : 14,
  C_PLAYER_RESPONSE : 15,
};
